enable-magisk-update = true
# patches-version = "v3.0.0-dev.4"


[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Hide Shorts dimming' 'Hide shortcuts' 'MaterialYou'"
excluded-patches = "'Settings for YouTube'"
patcher-args = "-OiconType=Cairo -OappIcon=mmt -OappName=YouTube -OdoubleTapLengthArrays=3, 5, 10, 15, 20, 30, 60, 120, 180 -OBackgroundColor=@android:color/transparent -OpackageNameYouTube=rvx.android.youtube -OpackageNameYouTubeMusic=rvx.android.youtube.music -OiconType=rounded -OchangeTopButtons=true -OsettingsLabel=eXtended -OinsertPosition=@string/about_key -OcornerRadius=4.0dip -OdarkThemeBackgroundColor=?ytBaseBackground -OlightThemeBackgroundColor=?ytBaseBackground -OstrokeColor=?attr/ytChipBackground -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white -OselectedTranslations=ar, id-rID, ja-rJP -OsettingsMenuIcon=yt_alt "

[Music]
enabled = false
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"
included-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Hide overlay filter' 'Hide player overlay filter' 'Change version code'"
excluded-patches = "'Enable debug logging'"
